#!/usr/bin/env python
import PySimpleGUI as sg
import os
import sys
from ice.analysis import multiple_sanger_analysis


if __name__ == "__main__":
    sg.theme("DarkPurple")

    layout = [
        [sg.Text("Select batch excel file[Required]:"), sg.Input(key="batch_xls"), sg.FileBrowse()],
        [sg.Text("Output folder[Optional]:"), sg.Input(key="outdir"), sg.FolderBrowse()],
        [sg.Button("Run")],
    ]

    window = sg.Window("GEB-ice", layout)

    while True:
        event, values = window.read()
        if event in (sg.WIN_CLOSED, "Exit"):
            break

        if event == "Run":
            batch_xls = os.path.abspath(values["batch_xls"])
            if not batch_xls:
                sg.popup_error("Select the batch excel file before click the Run botton")
            if not os.path.exists(batch_xls):
                sg.popup_error("Selected batch excel file not exists, check your input")
            outdir = values["outdir"]
            if not outdir:
                outdir = os.path.join(os.path.dirname(batch_xls), "results")
            if not os.path.exists(outdir):
                os.makedirs(outdir)

            data_dir = os.path.dirname(batch_xls)
            run_log_file = os.path.join(outdir, "run_log.txt")
            run_err_file = os.path.join(outdir, "run_err.txt")
            sys.stdout = open(run_log_file, "w")
            sys.stderr = open(run_err_file, "w")
            window["Run"].update(disabled=True)
            multiple_sanger_analysis(batch_xls, output_dir=outdir,data_dir=data_dir,verbose=True, single_line=None, allprops=True)
            window["Run"].update(disabled=False)
            os.startfile(outdir)


    window.close()
